package net.crystopia.crystalshard.paper.dhl.shared.enums.entities

import net.minecraft.world.entity.EntityType

enum class EntityType(val type: EntityType<*>) {

    ACACIA_BOAT(EntityType.ACACIA_BOAT),
    ACACIA_CHEST_BOAT(EntityType.ACACIA_CHEST_BOAT),
    ALLAY(EntityType.ALLAY),
    AREA_EFFECT_CLOUD(EntityType.AREA_EFFECT_CLOUD),
    ARMADILLO(EntityType.ARMADILLO),
    ARMOR_STAND(EntityType.ARMOR_STAND),
    ARROW(EntityType.ARROW),
    AXOLOTL(EntityType.AXOLOTL),
    BAMBOO_CHEST_RAFT(EntityType.BAMBOO_CHEST_RAFT),
    BAMBOO_RAFT(EntityType.BAMBOO_RAFT),
    BAT(EntityType.BAT),
    BEE(EntityType.BEE),
    BIRCH_BOAT(EntityType.BIRCH_BOAT),
    BIRCH_CHEST_BOAT(EntityType.BIRCH_CHEST_BOAT),
    BLAZE(EntityType.BLAZE),
    BOGGED(EntityType.BOGGED),
    BREEZE(EntityType.BREEZE),
    BREEZE_WIND_CHARGE(EntityType.BREEZE_WIND_CHARGE),
    CAMEL(EntityType.CAMEL),
    CAT(EntityType.CAT),
    CAVE_SPIDER(EntityType.CAVE_SPIDER),
    CHERRY_BOAT(EntityType.CHERRY_BOAT),
    CHERRY_CHEST_BOAT(EntityType.CHERRY_CHEST_BOAT),
    CHEST_MINECART(EntityType.CHEST_MINECART),
    CHICKEN(EntityType.CHICKEN),
    COD(EntityType.COD),
    COMMAND_BLOCK_MINECART(EntityType.COMMAND_BLOCK_MINECART),
    COW(EntityType.COW),
    CREEPER(EntityType.CREEPER),
    DARK_OAK_BOAT(EntityType.DARK_OAK_BOAT),
    DARK_OAK_CHEST_BOAT(EntityType.DARK_OAK_CHEST_BOAT),
    DOLPHIN(EntityType.DOLPHIN),
    DONKEY(EntityType.DONKEY),
    DRAGON_FIREBALL(EntityType.DRAGON_FIREBALL),
    DROWNED(EntityType.DROWNED),

    EGG(EntityType.EGG),
    ELDER_GUARDIAN(EntityType.ELDER_GUARDIAN),
    ENDERMAN(EntityType.ENDERMAN),
    ENDERMITE(EntityType.ENDERMITE),
    ENDER_DRAGON(EntityType.ENDER_DRAGON),
    ENDER_PEARL(EntityType.ENDER_PEARL),
    END_CRYSTAL(EntityType.END_CRYSTAL),
    EVOKER(EntityType.EVOKER),
    EVOKER_FANGS(EntityType.EVOKER_FANGS),
    EXPERIENCE_BOTTLE(EntityType.EXPERIENCE_BOTTLE),
    EXPERIENCE_ORB(EntityType.EXPERIENCE_ORB),
    EYE_OF_ENDER(EntityType.EYE_OF_ENDER),
    FALLING_BLOCK(EntityType.FALLING_BLOCK),
    FIREBALL(EntityType.FIREBALL),
    FIREWORK_ROCKET(EntityType.FIREWORK_ROCKET),
    FOX(EntityType.FOX),
    FROG(EntityType.FROG),
    FURNACE_MINECART(EntityType.FURNACE_MINECART),
    GHAST(EntityType.GHAST),
    HAPPY_GHAST(EntityType.HAPPY_GHAST),
    GIANT(EntityType.GIANT),
    GLOW_ITEM_FRAME(EntityType.GLOW_ITEM_FRAME),
    GLOW_SQUID(EntityType.GLOW_SQUID),
    GOAT(EntityType.GOAT),
    GUARDIAN(EntityType.GUARDIAN),
    HOGLIN(EntityType.HOGLIN),
    HOPPER_MINECART(EntityType.HOPPER_MINECART),
    HORSE(EntityType.HORSE),
    HUSK(EntityType.HUSK),
    ILLUSIONER(EntityType.ILLUSIONER),
    INTERACTION(EntityType.INTERACTION),
    IRON_GOLEM(EntityType.IRON_GOLEM),
    ITEM(EntityType.ITEM),
    ITEM_DISPLAY(EntityType.ITEM_DISPLAY),
    ITEM_FRAME(EntityType.ITEM_FRAME),

    JUNGLE_BOAT(EntityType.JUNGLE_BOAT),
    JUNGLE_CHEST_BOAT(EntityType.JUNGLE_CHEST_BOAT),

    LEASH_KNOT(EntityType.LEASH_KNOT),
    LIGHTNING_BOLT(EntityType.LIGHTNING_BOLT),
    LLAMA(EntityType.LLAMA),
    LLAMA_SPIT(EntityType.LLAMA_SPIT),
    MAGMA_CUBE(EntityType.MAGMA_CUBE),

    MANGROVE_BOAT(EntityType.MANGROVE_BOAT),
    MANGROVE_CHEST_BOAT(EntityType.MANGROVE_CHEST_BOAT),

    MARKER(EntityType.MARKER),
    MINECART(EntityType.MINECART),
    MOOSHROOM(EntityType.MOOSHROOM),
    MULE(EntityType.MULE),

    OAK_BOAT(EntityType.OAK_BOAT),
    OAK_CHEST_BOAT(EntityType.OAK_CHEST_BOAT),
    OCELOT(EntityType.OCELOT),

    PAINTING(EntityType.PAINTING),

    PALE_OAK_BOAT(EntityType.PALE_OAK_BOAT),
    PALE_OAK_CHEST_BOAT(EntityType.PALE_OAK_CHEST_BOAT),

    PANDA(EntityType.PANDA),
    PARROT(EntityType.PARROT),
    PHANTOM(EntityType.PHANTOM),
    PIG(EntityType.PIG),
    PIGLIN(EntityType.PIGLIN),
    PIGLIN_BRUTE(EntityType.PIGLIN_BRUTE),
    PILLAGER(EntityType.PILLAGER),
    POLAR_BEAR(EntityType.POLAR_BEAR),

    TEXT_DISPLAY(EntityType.TEXT_DISPLAY),
    PLAYER(EntityType.PLAYER);

}
