package net.crystopia.crystalshard.paper.dhl.shared.enums.gui

enum class ButtonType {
    LEFT_MOUSE_CLICK,
    RIGHT_MOUSE_CLICK,
    LEFT_CLICK_OUTSIDE,
    RIGHT_CLICK_OUTSIDE,
    SHIFT_LEFT_CLICK,
    SHIFT_RIGHT_CLICK,
    NUMBER_KEY_ONE,
    NUMBER_KEY_TWO,
    NUMBER_KEY_THREE,
    NUMBER_KEY_NINE,
    SWAP_KEY_F,
    MIDDLE_CLICK,
    DROP,
    CONTROL_DROP,
    START_LEFT_DRAG,
    START_RIGHT_DRAG,
    START_MIDDLE_DRAG,
    ADD_SLOT_LEFT_DRAG,
    ADD_SLOT_RIGHT_DRAG,
    ADD_SLOT_MIDDLE_DRAG,
    END_LEFT_DRAG,
    END_RIGHT_DRAG,
    END_MIDDLE_DRAG,
    DOUBLE_CLICK,
    UNKNOWN
}