package net.crystopia.crystalshard.paper.dhl.versions.v1_21_10.converter.enums.particles

import net.minecraft.core.particles.BlockParticleOption
import net.minecraft.core.particles.ColorParticleOption
import net.minecraft.core.particles.DustColorTransitionOptions
import net.minecraft.core.particles.DustParticleOptions
import net.minecraft.core.particles.ItemParticleOption
import net.minecraft.core.particles.ParticleType
import net.minecraft.core.particles.ParticleTypes
import net.minecraft.core.particles.PowerParticleOption
import net.minecraft.core.particles.ShriekParticleOption
import net.minecraft.core.particles.SpellParticleOption
import net.minecraft.core.particles.TrailParticleOption
import net.minecraft.core.particles.VibrationParticleOption

enum class ParticleType(val id : ParticleType<*>) {
    ANGRY_VILLAGER(ParticleTypes.ANGRY_VILLAGER),
    BLOCK(ParticleTypes<BlockParticleOption>.BLOCK),
    BLOCK_MARKER(ParticleTypes<BlockParticleOption>.BLOCK_MARKER),
    BUBBLE(ParticleTypes.BUBBLE),
    CLOUD(ParticleTypes.CLOUD),
    COPPER_FIRE_FLAME(ParticleTypes.COPPER_FIRE_FLAME),
    CRIT(ParticleTypes.CRIT),
    DAMAGE_INDICATOR(ParticleTypes.DAMAGE_INDICATOR),
    DRAGON_BREATH(ParticleTypes<PowerParticleOption>.DRAGON_BREATH),
    DRIPPING_LAVA(ParticleTypes.DRIPPING_LAVA),
    FALLING_LAVA(ParticleTypes.FALLING_LAVA),
    LANDING_LAVA(ParticleTypes.LANDING_LAVA),
    DRIPPING_WATER(ParticleTypes.DRIPPING_WATER),
    FALLING_WATER(ParticleTypes.FALLING_WATER),
    DUST(ParticleTypes<DustParticleOptions>.DUST),
    DUST_COLOR_TRANSITION(ParticleTypes<DustColorTransitionOptions>.DUST_COLOR_TRANSITION),
    EFFECT(ParticleTypes<SpellParticleOption>.EFFECT),
    ELDER_GUARDIAN(ParticleTypes.ELDER_GUARDIAN),
    ENCHANTED_HIT(ParticleTypes.ENCHANTED_HIT),
    ENCHANT(ParticleTypes.ENCHANT),
    END_ROD(ParticleTypes.END_ROD),
    ENTITY_EFFECT(ParticleTypes<ColorParticleOption>.ENTITY_EFFECT),
    EXPLOSION_EMITTER(ParticleTypes.EXPLOSION_EMITTER),
    EXPLOSION(ParticleTypes.EXPLOSION),
    GUST(ParticleTypes.GUST),
    SMALL_GUST(ParticleTypes.SMALL_GUST),
    GUST_EMITTER_LARGE(ParticleTypes.GUST_EMITTER_LARGE),
    GUST_EMITTER_SMALL(ParticleTypes.GUST_EMITTER_SMALL),
    SONIC_BOOM(ParticleTypes.SONIC_BOOM),
    FALLING_DUST(ParticleTypes<BlockParticleOption>.FALLING_DUST),
    FIREWORK(ParticleTypes.FIREWORK),
    FISHING(ParticleTypes.FISHING),
    FLAME(ParticleTypes.FLAME),
    INFESTED(ParticleTypes.INFESTED),
    CHERRY_LEAVES(ParticleTypes.CHERRY_LEAVES),
    PALE_OAK_LEAVES(ParticleTypes.PALE_OAK_LEAVES),
    TINTED_LEAVES(ParticleTypes<ColorParticleOption>.TINTED_LEAVES),
    SCULK_SOUL(ParticleTypes.SCULK_SOUL),
    SCULK_CHARGE(ParticleTypes.SCULK_CHARGE),
    SCULK_CHARGE_POP(ParticleTypes.SCULK_CHARGE_POP),
    SOUL_FIRE_FLAME(ParticleTypes.SOUL_FIRE_FLAME),
    SOUL(ParticleTypes.SOUL),
    FLASH(ParticleTypes<ColorParticleOption>.FLASH),
    HAPPY_VILLAGER(ParticleTypes.HAPPY_VILLAGER),
    COMPOSTER(ParticleTypes.COMPOSTER),
    HEART(ParticleTypes.HEART),
    INSTANT_EFFECT(ParticleTypes<SpellParticleOption>.INSTANT_EFFECT),
    ITEM(ParticleTypes<ItemParticleOption>.ITEM),
    VIBRATION(ParticleTypes<VibrationParticleOption>.VIBRATION),
    TRAIL(ParticleTypes<TrailParticleOption>.TRAIL),
    ITEM_SLIME(ParticleTypes.ITEM_SLIME),
    ITEM_COBWEB(ParticleTypes.ITEM_COBWEB),
    ITEM_SNOWBALL(ParticleTypes.ITEM_SNOWBALL),
    LARGE_SMOKE(ParticleTypes.LARGE_SMOKE),
    LAVA(ParticleTypes.LAVA),
    MYCELIUM(ParticleTypes.MYCELIUM),
    NOTE(ParticleTypes.NOTE),
    POOF(ParticleTypes.POOF),
    PORTAL(ParticleTypes.PORTAL),
    RAIN(ParticleTypes.RAIN),
    SMOKE(ParticleTypes.SMOKE),
    WHITE_SMOKE(ParticleTypes.WHITE_SMOKE),
    SNEEZE(ParticleTypes.SNEEZE),
    SPIT(ParticleTypes.SPIT),
    SQUID_INK(ParticleTypes.SQUID_INK),
    SWEEP_ATTACK(ParticleTypes.SWEEP_ATTACK),
    TOTEM_OF_UNDYING(ParticleTypes.TOTEM_OF_UNDYING),
    UNDERWATER(ParticleTypes.UNDERWATER),
    SPLASH(ParticleTypes.SPLASH),
    WITCH(ParticleTypes.WITCH),
    BUBBLE_POP(ParticleTypes.BUBBLE_POP),
    CURRENT_DOWN(ParticleTypes.CURRENT_DOWN),
    BUBBLE_COLUMN_UP(ParticleTypes.BUBBLE_COLUMN_UP),
    NAUTILUS(ParticleTypes.NAUTILUS),
    DOLPHIN(ParticleTypes.DOLPHIN),
    CAMPFIRE_COSY_SMOKE(ParticleTypes.CAMPFIRE_COSY_SMOKE),
    CAMPFIRE_SIGNAL_SMOKE(ParticleTypes.CAMPFIRE_SIGNAL_SMOKE),
    DRIPPING_HONEY(ParticleTypes.DRIPPING_HONEY),
    FALLING_HONEY(ParticleTypes.FALLING_HONEY),
    LANDING_HONEY(ParticleTypes.LANDING_HONEY),
    FALLING_NECTAR(ParticleTypes.FALLING_NECTAR),
    FALLING_SPORE_BLOSSOM(ParticleTypes.FALLING_SPORE_BLOSSOM),
    ASH(ParticleTypes.ASH),
    CRIMSON_SPORE(ParticleTypes.CRIMSON_SPORE),
    WARPED_SPORE(ParticleTypes.WARPED_SPORE),
    SPORE_BLOSSOM_AIR(ParticleTypes.SPORE_BLOSSOM_AIR),
    DRIPPING_OBSIDIAN_TEAR(ParticleTypes.DRIPPING_OBSIDIAN_TEAR),
    FALLING_OBSIDIAN_TEAR(ParticleTypes.FALLING_OBSIDIAN_TEAR),
    LANDING_OBSIDIAN_TEAR(ParticleTypes.LANDING_OBSIDIAN_TEAR),
    REVERSE_PORTAL(ParticleTypes.REVERSE_PORTAL),
    WHITE_ASH(ParticleTypes.WHITE_ASH),
    SMALL_FLAME(ParticleTypes.SMALL_FLAME),
    SNOWFLAKE(ParticleTypes.SNOWFLAKE),
    DRIPPING_DRIPSTONE_LAVA(ParticleTypes.DRIPPING_DRIPSTONE_LAVA),
    FALLING_DRIPSTONE_LAVA(ParticleTypes.FALLING_DRIPSTONE_LAVA),
    DRIPPING_DRIPSTONE_WATER(ParticleTypes.DRIPPING_DRIPSTONE_WATER),
    FALLING_DRIPSTONE_WATER(ParticleTypes.FALLING_DRIPSTONE_WATER),
    GLOW_SQUID_INK(ParticleTypes.GLOW_SQUID_INK),
    GLOW(ParticleTypes.GLOW),
    WAX_ON(ParticleTypes.WAX_ON),
    WAX_OFF(ParticleTypes.WAX_OFF),
    ELECTRIC_SPARK(ParticleTypes.ELECTRIC_SPARK),
    SCRAPE(ParticleTypes.SCRAPE),
    SHRIEK(ParticleTypes<ShriekParticleOption>.SHRIEK),
    EGG_CRACK(ParticleTypes.EGG_CRACK),
    DUST_PLUME(ParticleTypes.DUST_PLUME),
    TRIAL_SPAWNER_DETECTED_PLAYER(ParticleTypes.TRIAL_SPAWNER_DETECTED_PLAYER),
    TRIAL_SPAWNER_DETECTED_PLAYER_OMINOUS(ParticleTypes.TRIAL_SPAWNER_DETECTED_PLAYER_OMINOUS),
    VAULT_CONNECTION(ParticleTypes.VAULT_CONNECTION),
    DUST_PILLAR(ParticleTypes<BlockParticleOption>.DUST_PILLAR),
    OMINOUS_SPAWNING(ParticleTypes.OMINOUS_SPAWNING),
    RAID_OMEN(ParticleTypes.RAID_OMEN),
    TRIAL_OMEN(ParticleTypes.TRIAL_OMEN),
    BLOCK_CRUMBLE(ParticleTypes<BlockParticleOption>.BLOCK_CRUMBLE),
    FIREFLY(ParticleTypes.FIREFLY);

    companion object {
        fun convert(type: net.crystopia.crystalshard.paper.dhl.shared.enums.particles.ParticleType): net.crystopia.crystalshard.paper.dhl.versions.v1_21_10.converter.enums.particles.ParticleType {
            return net.crystopia.crystalshard.paper.dhl.versions.v1_21_10.converter.enums.particles.ParticleType.valueOf(
                type.name
            )
        }
    }

}